name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push alpine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-alpine
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:alpine-${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:buildcache,mode=max

      - name: Build and push java
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-java
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:java-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:java-${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/kubectl-helm-iam-authenticator:buildcache,mode=max
